/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legyenonismilliomos;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import model.Kerdes;

/**
 *
 * @author Akos
 */
public class KerdesAdatokDialog extends javax.swing.JDialog {

    
    private Kerdes kerdes; // adattag 
    private boolean mentes;
   
    
    public KerdesAdatokDialog(java.awt.Frame parent, boolean modal, Kerdes kerdes) {  // Kerdes kerdes paraméterként lett átvéve
        super(parent, modal);
        initComponents();
       
        setLocationRelativeTo(parent);  // Középre helyezi az indításnál parent a szülő ablakhoz igazítja
        mentes = false;
        
        this.kerdes = kerdes;  
        if (kerdes == null) {
            setTitle("Új kérdés felvétele");  // új kérdés felvétele
        }else {  // modosítás
            setTitle("Kérdés módosítása");
            tfKerdes.setText(kerdes.getKerdes());
            tfValasz1.setText(kerdes.getValasz1());
            tfValasz2.setText(kerdes.getValasz2());
            tfValasz3.setText(kerdes.getValasz3());
            tfValasz4.setText(kerdes.getValasz4());

            //  Rádió gombok állapotának betöltése a válasznak megfelelően
            switch(kerdes.getHelyesvalasz()){
                case 1 :
                    rbValasz1.setSelected(true);
                    break;
                case 2 :
                    rbValasz2.setSelected(true);
                    break;
                case 3 :
                    rbValasz3.setSelected(true);
                    break;  
                case 4 : 
                    rbValasz4.setSelected(true);
                    break;     
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfKerdes = new javax.swing.JTextField();
        tfValasz1 = new javax.swing.JTextField();
        btnMegsem = new javax.swing.JButton();
        btnMentes = new javax.swing.JButton();
        tfValasz2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfValasz3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfValasz4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rbValasz1 = new javax.swing.JRadioButton();
        rbValasz2 = new javax.swing.JRadioButton();
        rbValasz3 = new javax.swing.JRadioButton();
        rbValasz4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Kérdés:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Válasz 1: ");

        tfKerdes.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        tfKerdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKerdesActionPerformed(evt);
            }
        });

        tfValasz1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnMegsem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMegsem.setText("Mégsem");
        btnMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegsemActionPerformed(evt);
            }
        });

        btnMentes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnMentes.setText("Mentés");
        btnMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMentesActionPerformed(evt);
            }
        });

        tfValasz2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tfValasz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValasz2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Válasz 2: ");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Válasz 3:");

        tfValasz3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Válasz 4:");

        tfValasz4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Kérem válassza ki a kérdéshez tartozó helyes válasz számát: ");

        buttonGroup1.add(rbValasz1);
        rbValasz1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbValasz1.setText("Válasz 1");

        buttonGroup1.add(rbValasz2);
        rbValasz2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbValasz2.setText("Válasz 2");

        buttonGroup1.add(rbValasz3);
        rbValasz3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbValasz3.setText("Válasz 3");

        buttonGroup1.add(rbValasz4);
        rbValasz4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rbValasz4.setText("Válasz 4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbValasz1)
                    .addComponent(rbValasz2)
                    .addComponent(rbValasz4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbValasz3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(rbValasz1)
                .addGap(72, 72, 72)
                .addComponent(rbValasz2)
                .addGap(72, 72, 72)
                .addComponent(rbValasz3)
                .addGap(72, 72, 72)
                .addComponent(rbValasz4)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfKerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfValasz3, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfValasz4, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfValasz1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfValasz2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMentes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMegsem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMegsem, btnMentes});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfValasz2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfValasz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfValasz3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfValasz4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMentes)
                    .addComponent(btnMegsem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfKerdes, tfValasz1, tfValasz2});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMegsem, btnMentes});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMentesActionPerformed
        mentes = true;
        boolean radiovalaszt = false;
        
        if (kerdes == null) { 
            kerdes = new Kerdes(); // új kérdés felvétele
        }  // módosítás
            kerdes.setKerdes(tfKerdes.getText());
            kerdes.setValasz1(tfValasz1.getText());
            kerdes.setValasz2(tfValasz2.getText());
            kerdes.setValasz3(tfValasz3.getText());
            kerdes.setValasz4(tfValasz4.getText());
            
            // Rádió gombok szerint a helyes válasz mentése
            if ( rbValasz1.isSelected()) {
                kerdes.setHelyesvalasz(1);
                radiovalaszt = true;
            } else if (rbValasz2.isSelected()) {
                kerdes.setHelyesvalasz(2);
                radiovalaszt = true;
            } else if (rbValasz3.isSelected()) {
                kerdes.setHelyesvalasz(3);
                radiovalaszt = true;
            } else if (rbValasz4.isSelected()) {
                kerdes.setHelyesvalasz(4);
                radiovalaszt = true;
            } 
            
        // Csak akkor engedi tovább ha minden mezőbe van szöveg és valamelyik rádiógomb is ki lett választva
        if (kerdes.getKerdes().isEmpty() == true || kerdes.getValasz1().isEmpty() == true || kerdes.getValasz2().isEmpty() || kerdes.getValasz3().isEmpty() || kerdes.getValasz4().isEmpty() || radiovalaszt == false ) {
            JOptionPane.showMessageDialog(null, "Üres adat mező ! Kérem töltse ki a kérdés / válasz mezőt !","Hibás adat !",JOptionPane.WARNING_MESSAGE);
            setVisible(true);
            mentes = false;
        } else if (kerdes.getKerdes().length() > 80) {
            JOptionPane.showMessageDialog(null, "A kérdéshez maximum 80 karaktert írhat.","Hibás adat !",JOptionPane.WARNING_MESSAGE);
            setVisible(true);
            mentes = false;
        } else if (kerdes.getValasz1().length() > 55 || kerdes.getValasz2().length() > 55 || kerdes.getValasz3().length() > 55 || kerdes.getValasz4().length() > 55) {
            JOptionPane.showMessageDialog(null, "A válaszokhoz maximum 55 karaktert írhat.","Hibás adat !",JOptionPane.WARNING_MESSAGE);
            setVisible(true);
            mentes = false;
        }else {
            showMessageDialog(null, "Az adatok az adatbázisba lettek mentve.");
            setVisible(false);
        }
    }//GEN-LAST:event_btnMentesActionPerformed

    private void tfValasz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValasz2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValasz2ActionPerformed

    private void tfKerdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKerdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKerdesActionPerformed

    private void btnMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegsemActionPerformed
        setVisible(false);  // Mégsem gomb , eltünteti az ablakot
    }//GEN-LAST:event_btnMegsemActionPerformed

    public Kerdes getKerdes() {
        return kerdes;
    }

    public boolean isMentes() {
        return mentes;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMegsem;
    private javax.swing.JButton btnMentes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbValasz1;
    private javax.swing.JRadioButton rbValasz2;
    private javax.swing.JRadioButton rbValasz3;
    private javax.swing.JRadioButton rbValasz4;
    private javax.swing.JTextField tfKerdes;
    private javax.swing.JTextField tfValasz1;
    private javax.swing.JTextField tfValasz2;
    private javax.swing.JTextField tfValasz3;
    private javax.swing.JTextField tfValasz4;
    // End of variables declaration//GEN-END:variables

   
}
